/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package view;

import connection.ConnectionDados;
import static connection.ConnectionDados.PASS;
import static connection.ConnectionDados.USER;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Beleza Charmosa 2
 */

public class ConfBanco extends javax.swing.JFrame {
    private boolean VERIFICADO = false;
    

    /** Creates new form ConfBanco */
    public ConfBanco() {
        initComponents();
        Read_Conf();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtHost = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPorta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        btnTestar = new javax.swing.JButton();
        btnConectar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Configuração do Banco de Dados");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Host");

        txtHost.setText("localhost");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Porta");

        txtPorta.setText("3306");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Usuário");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Senha");

        btnTestar.setText("Testar");
        btnTestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestarActionPerformed(evt);
            }
        });

        btnConectar.setText("Conectar");
        btnConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2)
                                    .addComponent(txtHost)
                                    .addComponent(txtUser, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPass)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel3)
                                            .addComponent(txtPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTestar)
                                .addGap(33, 33, 33)
                                .addComponent(btnConectar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(347, 347, 347)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHost, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTestar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConectar))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnConectar, btnTestar});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarActionPerformed
        // TODO add your handling code here:
       ConnectionDados.HOST = txtHost.getText();
       ConnectionDados.PORTA = txtPorta.getText();
       ConnectionDados.USER = txtUser.getText();
       ConnectionDados.PASS = new String(txtPass.getPassword()).trim();
       String url ="jdbc:mysql://" + ConnectionDados.HOST  + ":" + ConnectionDados.PORTA + "";
       Connection con = null; 
        try {
            con = DriverManager.getConnection(url, USER, PASS);
        } catch (SQLException ex) {
            Logger.getLogger(ConfBanco.class.getName()).log(Level.SEVERE, null, ex);
        }

        if(Grava_Conf()){
            if(Read_Conf()){
                if(ConnectionDados.Cria_tabelas()){
                    ConnectionDados.closeConnection(con);
                    new login().setVisible(true);
                    dispose();
                }
            }
        }
    }//GEN-LAST:event_btnConectarActionPerformed
private boolean Grava_Conf(){
boolean grava = false;
try{
    File diretorio = new File("C:\\Estacionamento\\Configuracao");
    if(!diretorio.exists()){
    diretorio.mkdirs();
    }
    FileWriter arquivo = new FileWriter("C:\\Estacionamento\\Configuracao\\conexao.ini");
    PrintWriter gravaArq = new PrintWriter(arquivo);
    gravaArq.println(txtHost.getText());
    gravaArq.println(txtPorta.getText());
    gravaArq.println(txtUser.getText());
    gravaArq.println(new String(txtPass.getPassword()).trim());
    arquivo.close();
    grava = true;
    
}catch(IOException erro){
    JOptionPane.showMessageDialog(null, "Sem permissão para configurar o sistema."+ erro +"","Erro !",0);
}
return grava;
}
private boolean Read_Conf(){
    boolean read = false;
    try {
        String linha;
        String arquivo = "C:\\Estacionamento\\Configuracao\\conexao.ini";
        int cont = 0;
        File arq = new File(arquivo);
        
        if (arq.exists()) {
            
            FileReader reader = new FileReader(arq);
            BufferedReader leitor = new BufferedReader(reader);
            while (true) {                
                linha = leitor.readLine();
                if(cont ==0){
                txtHost.setText(linha);
                ConnectionDados.HOST = txtHost.getText();
                }
                if(cont ==1){
                txtPorta.setText(linha);
                ConnectionDados.PORTA = txtPorta.getText();
                }
                if(cont ==2){
                txtUser.setText(linha);
                ConnectionDados.USER = txtUser.getText();
                }
                if(cont >=3){
                txtPass.setText(linha);
                ConnectionDados.PASS = new String(txtPass.getPassword()).trim();
                break;
                }
                 
                System.err.println(linha + "\n");
                cont++;
            }
             boolean con = ConnectionDados.getConnection(txtHost.getText(), txtPorta.getText(), txtUser.getText(), new String(txtPass.getPassword()).trim());
       if(con){
      read = true;
     btnConectar.setEnabled(true);
     // new ConfBanco().setVisible(false);
      //new login().setVisible(true);
     
       }else{
        btnConectar.setEnabled(false);
       }
        }
        
    } catch (Exception erro) {
    }
return read;
}
    private void btnTestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestarActionPerformed
        // TODO add your handling code here:
        boolean con = ConnectionDados.getConnection(txtHost.getText(), txtPorta.getText(), txtUser.getText(), new String(txtPass.getPassword()).trim());
       if(con){
       JOptionPane.showMessageDialog(null, "Teste realizada com sucesso!");
       
       btnConectar.setEnabled(true);
       }else{
       btnConectar.setEnabled(false);
       }
       Grava_Conf();
       
    }//GEN-LAST:event_btnTestarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        ConfBanco tela = new ConfBanco();
        
        if (tela.Read_Conf()){
        if(ConnectionDados.Cria_tabelas()){
            tela.VERIFICADO = true;
            Connection con = ConnectionDados.getConnection();
            ConnectionDados.closeConnection(con);
            new login().setVisible(true);
        }
        }
        
       if(tela.VERIFICADO == false){
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfBanco().setVisible(true);
            }
        });
       }
    }





    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConectar;
    private javax.swing.JButton btnTestar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtHost;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtPorta;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

}
